name: ucl
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - uproot
  - matplotlib=3.7
  - pandas
  - jupyterlab
  - numpy
  - pytest
  - lmfit
  - tqdm
  - ipywidgets
